---

# Jenkins Configuration setup

  - name: Create jenkins configuration
    file:
      path: /etc/sysconfig/jenkins
      state: touch

  - name: Configure Jenkins
    lineinfile:
      dest: /etc/sysconfig/jenkins
      regexp: "^{{ item.key }}="
      line: "{{ item.key }}={{ item.value }}"
    with_dict: "{{ jenkins_configs }}"
    when: item.value
    register: config_changed

  - name: Add Jenkins user into sudoers for sudo access
    lineinfile:
      dest: /etc/sudoers
      line: "{{ item.line }}"
      create: yes
      state: present
    with_items:
      - { line: 'jenkins  ALL=(ALL)   NOPASSWD: ALL' }
      - { line: 'Defaults:jenkins !requiretty' }

  - name: Restart jenkins now
    service: name=jenkins state=restarted enabled=yes
    when: config_changed.changed

